export const technologies = [
  "Webflow: No Code Web Builder for creating responsive websites visually",
  "Next.js: Full-Stack React Framework with server-side rendering and static site generation",
  "Node.js: JavaScript Runtime for building scalable backend applications",
  "PostgreSQL: Relational Database known for reliability, robustness, and performance",
  "MongoDB: NoSQL Document Database optimized for unstructured data storage",
  "Firebase: Backend-as-a-Service (BaaS) with real-time database, authentication, and hosting",
  "AWS: Cloud Computing Services offering scalable infrastructure and storage solutions",
  "Vercel: Serverless Deployment Platform optimized for frontend frameworks like Next.js",
  "Netlify: Jamstack Deployment Platform with automated CI/CD for frontend apps",
  "React: Frontend UI Library for building interactive user interfaces",
  "Vue.js: Progressive JavaScript Framework with an easy learning curve",
  "Angular: Web Application Framework maintained by Google for large-scale apps",
  "Django: Python Web Framework with built-in authentication and ORM support",
  "Flask: Lightweight Python Web Framework for microservices and APIs",
  "FastAPI: High-Performance API Framework for building asynchronous web applications",
  "Express.js: Minimalist Web Framework for Node.js to build fast APIs",
  "Spring Boot: Java Framework for Backend development with built-in microservices support",
  "Laravel: PHP Web Framework for clean, simple, and scalable web development",
  "Ruby on Rails: Web Framework for Ruby that emphasizes convention over configuration",
  "Socket.io: Real-Time WebSockets for chat apps, live notifications, and gaming",
  "GraphQL: API Query Language for flexible and efficient data fetching",
  "REST API: Standard API Architecture for easy and scalable communication between systems",
  "Supabase: Open-Source Firebase Alternative with PostgreSQL backend",
  "Strapi: Headless CMS with GraphQL support and customizable API",
  "Sanity: Headless CMS for Structured Content with real-time collaboration",
  "Shopify: E-commerce Platform for creating and managing online stores",
  "WooCommerce: WordPress E-commerce Plugin for turning WordPress sites into stores",
  "Magento: Scalable E-commerce Solution with enterprise-level customization",
  "WordPress: Popular CMS for creating blogs, business websites, and e-commerce stores",
  "Three.js: 3D Graphics in the Browser for animations and VR experiences",
  "Babylon.js: 3D Game Engine for Web with physics and rendering capabilities",
  "Unity: Game Development Engine for 2D, 3D, AR, and VR experiences",
  "Unreal Engine: High-End Game Development Engine for photorealistic visuals",
  "TensorFlow: Machine Learning Library for deep learning and AI model training",
  "PyTorch: Deep Learning Framework popular in AI research and production",
  "LangChain: AI-Powered Language Processing for building LLM-based applications",
  "GPT-4: OpenAI Language Model for chatbots, content generation, and automation",
  "OpenCV: Computer Vision Library for image processing and object detection",
  "Whisper AI: Speech-to-Text Model by OpenAI for automatic transcription",
  "WebRTC: Real-Time Communication for video calls and peer-to-peer networking",
  "Solidity: Smart Contract Programming Language for Ethereum blockchain",
  "Hardhat: Ethereum Development Environment for testing and deploying smart contracts",
  "Foundry: Next-Gen Smart Contract Framework with high-performance testing",
  "Alpaca API: Algorithmic Trading platform for automated stock trading",
  "SendGrid: Email API & Marketing Service for bulk email campaigns",
  "Stripe: Payment Processing API for handling secure online transactions",
  "Twilio: Communication API (SMS, Voice) for integrating messaging into apps",
  "Rasa: Conversational AI Platform for building intelligent chatbots",
  "Elasticsearch: Full-Text Search Engine for fast and scalable search applications",
  "Kibana: Data Visualization for Elasticsearch to monitor logs and metrics",
  "Redis: In-Memory Key-Value Store for caching and real-time data processing",
  "Kafka: Distributed Event Streaming Platform for real-time data pipelines",
  "Docker: Containerization Platform for packaging applications into isolated environments",
  "Kubernetes: Container Orchestration for scaling and managing containerized applications",
  "AWS Lambda: Serverless Function Computing for executing code without managing servers",
  "Terraform: Infrastructure as Code (IaC) tool for automating cloud deployments",
  "Ansible: IT Automation and Configuration Management tool",
  "Jenkins: Continuous Integration and Deployment (CI/CD) tool",
  "GitHub Actions: CI/CD automation built into GitHub repositories",
  "CircleCI: Cloud-based CI/CD service for DevOps automation",
  "Travis CI: CI/CD tool for testing and deploying applications",
  "Pulumi: Modern Infrastructure as Code using TypeScript, Python, and Go",
  "Cypress: End-to-End Testing framework for web applications",
  "Playwright: Web Testing Automation tool by Microsoft",
  "Jest: JavaScript Testing Framework for unit and integration tests",
  "Mocha: Feature-rich JavaScript Test Framework running on Node.js",
  "Chai: Assertion Library for Node.js and browser testing",
  "Storybook: UI Development Environment for Component Libraries",
  "WebSockets: Protocol for real-time data exchange between client and server",
  "gRPC: High-Performance Remote Procedure Call (RPC) framework",
  "OpenAPI: API Specification for designing and documenting RESTful APIs",
  "Postman: API Testing and Collaboration Tool",
  "Swagger: API Documentation and Development tool",
  "Tailwind CSS: Utility-First CSS Framework for fast UI development",
  "Bootstrap: Popular Frontend Framework with responsive design",
  "Material UI: UI Component Library for React applications",
  "Ant Design: Enterprise UI Framework for React",
  "Svelte: JavaScript Framework with a focus on speed and minimal bundle size",
  "Nuxt.js: Framework for building Vue.js applications with SSR support",
  "Remix: Full-stack React framework for building modern web applications",
  "Blitz.js: Full-stack framework for building production-ready apps",
  "Electron: Cross-Platform Desktop App Framework using JavaScript",
  "Capacitor: Cross-Platform Native Runtime for mobile apps",
  "Ionic: Framework for building hybrid mobile applications",
  "Flutter: UI Toolkit by Google for building natively compiled mobile apps",
  "Dart: Programming Language used with Flutter",
  "Swift: Apple's official language for iOS and macOS development",
  "Kotlin: Modern, concise language for Android development",
  "Go (Golang): Fast, statically typed language for backend services",
  "Rust: Systems programming language focused on safety and performance",
  "C#: General-purpose language mainly used for game and enterprise applications",
  "ASP.NET: Microsoft Web Framework for building web applications and APIs",
  "PHP: Server-side scripting language for web development",
  "C++: High-performance programming language used in game engines and system software",
  "Ruby: Dynamic, object-oriented programming language",
  "Perl: General-purpose programming language known for text processing",
  "Lua: Lightweight scripting language used in game development",
  "Graphite: Monitoring and Performance Metrics tool",
  "Prometheus: Monitoring and Alerting toolkit for Kubernetes and cloud infrastructure",
  "Datadog: Cloud Monitoring and Security Platform for DevOps teams",
  "New Relic: Application Performance Monitoring (APM) tool",
  "Logstash: Data Processing Pipeline for logs and events",
  "Fluentd: Open-Source Data Collector for log processing",
];
